name: CI Pipeline

# Kích hoạt workflow khi có sự kiện push hoặc pull request trên nhánh main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout repository
        uses: actions/checkout@v3

      # Bước 2: Cài đặt Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Hoặc 'zulu', 'adopt', v.v.
          java-version: '17'

      # Bước 3: Cài đặt Maven (nếu sử dụng Maven)
      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Verify Maven version
        run: mvn -version

      # Bước 4: Cài đặt ChromeDriver (cho Selenium)
      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: '129.0.6668.89' # Thay bằng phiên bản ChromeDriver tương thích

      # Bước 5: Cài đặt Chrome Browser
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      # Bước 6: Xây dựng dự án
      - name: Build with Maven
        run: mvn clean install

      # Bước 7: Chạy các bài kiểm thử
      - name: Run Tests
        run: mvn test
